# Generated by Django 3.0.4 on 2020-03-07 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Número')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Altura')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Peso')),
                ('evolve_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evolve_to', to='pokedex.Pokemon', verbose_name='Forma Evolutiva')),
                ('type_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokemon_type_1', to='pokedex.Type', verbose_name='Tipo 1')),
                ('type_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pokemon_type_2', to='pokedex.Type', verbose_name='Tipo 2')),
            ],
            options={
                'verbose_name': 'Pokemon',
                'verbose_name_plural': 'Pokemon',
            },
        ),
    ]
